<a href="https://colab.research.google.com/github/Fazin/Data_Science-Study/blob/main/Desafio_Codenation_Notas_ENEM_2016.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Descubra as melhores notas de matemática do ENEM 2016
Você deverá criar um modelo para prever a nota da prova de matemática de quem participou do ENEM 2016.

Tópicos
Neste desafio você aprenderá:

Lógica
Análise de dados
Estatística
Regression

Detalhes
O contexto do desafio gira em torno dos resultados do ENEM 2016 (disponíveis no arquivo train.csv). Este arquivo, e apenas ele, deve ser utilizado para todos os desafios. Qualquer dúvida a respeito das colunas, consulte o Dicionário dos Microdados do Enem 2016.

Muitas universidades brasileiras utilizam o ENEM para selecionar seus futuros alunos e alunas. Isto é feito com uma média ponderada das notas das provas de matemática, ciências da natureza, linguagens e códigos, ciências humanas e redação, com os pesos abaixo:

**matemática: 3
ciências da natureza: 2
linguagens e códigos: 1.5
ciências humanas: 1
redação: 3**

No arquivo test.csv crie um modelo para prever nota da prova de matemática (coluna NU_NOTA_MT) de quem participou do ENEM 2016.

Salve sua resposta em um arquivo chamado **answer.csv** com duas colunas: NU_INSCRICAO e NU_NOTA_MT.

Faça o upload do arquivo answer.csv usando o botão “Submeter resposta”.

Observações
O objetivo do desafio é avaliar a sua capacidade de resolver problemas, então ele pode ser resolvido em qualquer linguagem de programação ou ferramenta que você tenha facilidade. Mas recomendamos o uso de linguagens com maior ferramental de matemática e estatística como Python, R, Scala ou Julia.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [ ]:
train_set = pd.read_csv('train.csv')
test_set = pd.read_csv('test.csv')

display(train_set.head())

display(test_set)

   Unnamed: 0                              NU_INSCRICAO  ...  Q049  Q050
0           1  ed50e8aaa58e7a806c337585efee9ca41f1eb1ad  ...     B     D
1           2  2c3acac4b33ec2b195d77e7c04a2d75727fad723  ...     C     A
2           3  f4545f8ccb9ff5c8aad7d32951b3f251a26e6568  ...     B     A
3           4  3d6ec248fef899c414e77f82d5c6d2bffbeaf7fe  ...     A     A
4           5  bf896ac8d3ecadd6dba1dfbf50110afcbf5d3268  ...     A     A

[5 rows x 167 columns]

                                  NU_INSCRICAO  CO_UF_RESIDENCIA  ... Q027  Q047
0     73ff9fcc02f0a99919906c942c2e1a1042cdcf98                41  ...    C     A
1     71a95f9f1b91a82c65ad94abbdf9f54e6066f968                21  ...    F     A
2     b38a03232f43b11c9d0788abaf060f7366053b6d                23  ...  NaN     A
3     70b682d9a3636be23f6120fa9d6b164eb3c6002d                15  ...  NaN     A
4     715494628a50142ce8cb17191cfe6d0f3cae0934                41  ...  NaN     A
...                                        ...               ...  ...  ...   ...
4571  dac0f22429c7f8e3931d0abaf5dfc8e5c772a48b                41  ...  NaN     A
4572  a75fa8770257e7c9368d059fe53d9ef431f4bdef                35  ...  NaN     A
4573  655fa6306720ff16e825903b5422a46608a77545                35  ...  NaN     D
4574  1f4bc3e3d56212d500625bfe8ac78ccff4362293                52  ...  NaN     A
4575  adf0d15b54317b6564ef56dad2b775bbb0ef50cc                33  ...    B     A

[4576 rows x 47 columns]

In [ ]:
train_set.set_index(keys='NU_INSCRICAO', drop=True)

                                          Unnamed: 0  NU_ANO  ...  Q049 Q050
NU_INSCRICAO                                                  ...
ed50e8aaa58e7a806c337585efee9ca41f1eb1ad           1    2016  ...     B    D
2c3acac4b33ec2b195d77e7c04a2d75727fad723           2    2016  ...     C    A
f4545f8ccb9ff5c8aad7d32951b3f251a26e6568           3    2016  ...     B    A
3d6ec248fef899c414e77f82d5c6d2bffbeaf7fe           4    2016  ...     A    A
bf896ac8d3ecadd6dba1dfbf50110afcbf5d3268           5    2016  ...     A    A
...                                              ...     ...  ...   ...  ...
aadf671ef8c1c6efa42e69432093ab83c17a52ac        4582    2016  ...     A    A
461f7ef2753d9d5fa0b054930d6b0e0eec318e81        4583    2016  ...     A    A
5354503700ecf2388f68990435390b6e1ad454ee        4584    2016  ...     A    A
c7a9e94a42bd76b7978f13c013a61702e36cc42c        4585    2016  ...     A    D
0af8939c470a600b30bdaa80375ee0db848b0e35        4586    2016  ...     A    A

[13730 rows x 166 columns]

In [ ]:
new_train = train_set[['NU_INSCRICAO','NU_ANO', 'NO_MUNICIPIO_RESIDENCIA', 'CO_UF_RESIDENCIA','NU_IDADE', 'TP_SEXO', 'TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_NACIONALIDADE', 'CO_MUNICIPIO_NASCIMENTO', 'NO_MUNICIPIO_NASCIMENTO', 'CO_UF_NASCIMENTO', 'SG_UF_NASCIMENTO', 'TP_ST_CONCLUSAO', 'TP_ANO_CONCLUIU', 'TP_ESCOLA', 'TP_ENSINO', 'IN_TREINEIRO', 'CO_ESCOLA', 'CO_MUNICIPIO_ESC', 'NO_MUNICIPIO_ESC', 'CO_UF_ESC', 'SG_UF_ESC', 'TP_DEPENDENCIA_ADM_ESC', 'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC', 'IN_CERTIFICADO', 'NO_ENTIDADE_CERTIFICACAO', 'CO_UF_ENTIDADE_CERTIFICACAO', 'SG_UF_ENTIDADE_CERTIFICACAO', 'CO_MUNICIPIO_PROVA', 'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA', 'SG_UF_PROVA', 'TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC', 'TP_PRESENCA_MT', 'CO_PROVA_CN', 'CO_PROVA_CH', 'CO_PROVA_LC', 'CO_PROVA_MT', 'NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT', 'TX_RESPOSTAS_CN', 'TX_RESPOSTAS_CH', 'TX_RESPOSTAS_LC', 'TX_RESPOSTAS_MT', 'TP_LINGUA', 'TX_GABARITO_CN', 'TX_GABARITO_CH', 'TX_GABARITO_LC', 'TX_GABARITO_MT']
]

new_train.set_index(keys='NU_INSCRICAO')

check1 = new_train[['NU_INSCRICAO','TX_RESPOSTAS_MT','NU_NOTA_MT']]

check1 = check1[check1['NU_NOTA_MT'].notnull()]

check2 = check1['TX_RESPOSTAS_MT'].apply(lambda x: pd.Series(list(x)))

train_fit = pd.concat((check1,check2),join='inner',axis=1)

train_fit.columns = ['NU_INSCRICAO','TX_RESPOSTAS_MT','NU_NOTA_MT','Q_0', 'Q_1', 'Q_2', 'Q_3', 'Q_4', 'Q_5', 'Q_6', 'Q_7', 'Q_8', 'Q_9', 'Q_10', 'Q_11', 'Q_12', 'Q_13', 'Q_14', 'Q_15', 'Q_16', 'Q_17', 'Q_18', 'Q_19', 'Q_20', 'Q_21', 'Q_22', 'Q_23', 'Q_24', 'Q_25', 'Q_26', 'Q_27', 'Q_28', 'Q_29', 'Q_30', 'Q_31', 'Q_32', 'Q_33', 'Q_34', 'Q_35', 'Q_36', 'Q_37', 'Q_38', 'Q_39', 'Q_40', 'Q_41', 'Q_42', 'Q_43', 'Q_44']

display(train_fit.head())

test_1 = test_set[['NU_INSCRICAO','TX_RESPOSTAS_MT']]
test_1 = test_1[test_1['TX_RESPOSTAS_MT'].notnull()]
test_2 = test_1['TX_RESPOSTAS_MT'].apply(lambda x: pd.Series(list(x)))
test_fit = train_fit = pd.concat((test_1,test_2),join='inner',axis=1)
test_fit.columns = ['NU_INSCRICAO','TX_RESPOSTAS_MT','Q_0', 'Q_1', 'Q_2', 'Q_3', 'Q_4', 'Q_5', 'Q_6', 'Q_7', 'Q_8', 'Q_9', 'Q_10', 'Q_11', 'Q_12', 'Q_13', 'Q_14', 'Q_15', 'Q_16', 'Q_17', 'Q_18', 'Q_19', 'Q_20', 'Q_21', 'Q_22', 'Q_23', 'Q_24', 'Q_25', 'Q_26', 'Q_27', 'Q_28', 'Q_29', 'Q_30', 'Q_31', 'Q_32', 'Q_33', 'Q_34', 'Q_35', 'Q_36', 'Q_37', 'Q_38', 'Q_39', 'Q_40', 'Q_41', 'Q_42', 'Q_43', 'Q_44']

display(test_fit.head())

                               NU_INSCRICAO  ... Q_44
0  ed50e8aaa58e7a806c337585efee9ca41f1eb1ad  ...    A
1  2c3acac4b33ec2b195d77e7c04a2d75727fad723  ...    B
5  a37c99ec251d4f6e8ddbeabadf1c87fdbfddc4d1  ...    C
6  63b4e128e9ffe8ab27f5d093db1976ef4f353e0a  ...    A
7  2eb189d4912f64b19d1967e8e84b6141aba18770  ...    D

[5 rows x 48 columns]

KeyError: ignored

In [ ]:
import seaborn as sns
from statsmodels.formula.api import ols

model = ols('NU_NOTA_MT ~ C(Q_0) + C(Q_1) + C(Q_2) + C(Q_3) + C(Q_4) + C(Q_5) + C(Q_6) + C(Q_7) + C(Q_8) + C(Q_9) + C(Q_10) + C(Q_11) + C(Q_12) + C(Q_13) + C(Q_14) + C(Q_15) + C(Q_16) + C(Q_17) + C(Q_18) + C(Q_19) + C(Q_20) + C(Q_21) + C(Q_22) + C(Q_23) + C(Q_24) + C(Q_25) + C(Q_26) + C(Q_27) + C(Q_28) + C(Q_29) + C(Q_30) + C(Q_31) + C(Q_32) + C(Q_33) + C(Q_34) + C(Q_35) + C(Q_36) + C(Q_37) + C(Q_38) + C(Q_39) + C(Q_40) + C(Q_41) + C(Q_42) + C(Q_43) + C(Q_44)', data=train_fit)
fitted_model = model.fit()
fitted_model.summary()

model.predict()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             NU_NOTA_MT   R-squared:                       0.578
Model:                            OLS   Adj. R-squared:                  0.566
Method:                 Least Squares   F-statistic:                     49.97
Date:                Tue, 31 Mar 2020   Prob (F-statistic):               0.00
Time:                        18:36:53   Log-Likelihood:                -56656.
No. Observations:               10133   AIC:                         1.139e+05
Df Residuals:                    9862   BIC:                         1.158e+05
Df Model:                         270
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept      -26.1649    123.304     -0.212      0.832    -267.866     215.536
C(Q_0)[T..]     -5.6323     30.280     -0.186      0.852     -64.988      53.723
C(Q_0)[T.A]     -4.6210     24.071     -0.192      0.848     -51.805      42.563
C(Q_0)[T.B]     -5.6523     24.064     -0.235      0.814     -52.823      41.518
C(Q_0)[T.C]     31.5213     24.043      1.311      0.190     -15.608      78.651
C(Q_0)[T.D]     -2.5700     24.068     -0.107      0.915     -49.748      44.608
C(Q_0)[T.E]      2.8588     24.093      0.119      0.906     -44.368      50.085
C(Q_1)[T..]    -52.0957     34.264     -1.520      0.128    -119.260      15.068
C(Q_1)[T.A]      1.1933     31.033      0.038      0.969     -59.638      62.025
C(Q_1)[T.B]     -1.3762     31.052     -0.044      0.965     -62.244      59.492
C(Q_1)[T.C]     -4.3846     31.044     -0.141      0.888     -65.238      56.469
C(Q_1)[T.D]    -14.6172     31.063     -0.471      0.638     -75.508      46.273
C(Q_1)[T.E]      1.3761     31.054      0.044      0.965     -59.496      62.248
C(Q_2)[T..]     -9.1377     24.201     -0.378      0.706     -56.577      38.301
C(Q_2)[T.A]     20.6336     18.041      1.144      0.253     -14.731      55.999
C(Q_2)[T.B]      2.2248     18.036      0.123      0.902     -33.129      37.579
C(Q_2)[T.C]     -1.2767     18.042     -0.071      0.944     -36.643      34.090
C(Q_2)[T.D]     28.7941     18.037      1.596      0.110      -6.562      64.150
C(Q_2)[T.E]     32.9478     18.036      1.827      0.068      -2.406      68.301
C(Q_3)[T..]     26.8186     24.033      1.116      0.264     -20.290      73.928
C(Q_3)[T.A]     19.0614     16.259      1.172      0.241     -12.810      50.933
C(Q_3)[T.B]     18.6170     16.261      1.145      0.252     -13.257      50.491
C(Q_3)[T.C]     24.3311     16.240      1.498      0.134      -7.503      56.165
C(Q_3)[T.D]     11.7492     16.262      0.723      0.470     -20.127      43.626
C(Q_3)[T.E]     17.7234     16.276      1.089      0.276     -14.181      49.628
C(Q_4)[T..]    -47.1223     32.634     -1.444      0.149    -111.091      16.847
C(Q_4)[T.A]     -1.3355     18.584     -0.072      0.943     -37.764      35.093
C(Q_4)[T.B]     28.1310     18.585      1.514      0.130      -8.300      64.562
C(Q_4)[T.C]     20.8692     18.578      1.123      0.261     -15.547      57.285
C(Q_4)[T.D]     25.1298     18.577      1.353      0.176     -11.286      61.545
C(Q_4)[T.E]      6.1529     18.589      0.331      0.741     -30.285      42.590
C(Q_5)[T..]     12.6041     25.271      0.499      0.618     -36.933      62.141
C(Q_5)[T.A]     14.5073     18.596      0.780      0.435     -21.944      50.958
C(Q_5)[T.B]     25.8724     18.568      1.393      0.164     -10.525      62.270
C(Q_5)[T.C]     19.0572     18.585      1.025      0.305     -17.373      55.488
C(Q_5)[T.D]     11.8605     18.606      0.637      0.524     -24.611      48.332
C(Q_5)[T.E]     13.7078     18.590      0.737      0.461     -22.732      50.148
C(Q_6)[T..]    -53.2460     26.814     -1.986      0.047    -105.807      -0.685
C(Q_6)[T.A]     11.2749     18.086      0.623      0.533     -24.177      46.727
C(Q_6)[T.B]      9.3917     18.066      0.520      0.603     -26.022      44.806
C(Q_6)[T.C]     30.9414     18.066      1.713      0.087      -4.471      66.354
C(Q_6)[T.D]      7.4866     18.076      0.414      0.679     -27.947      42.920
C(Q_6)[T.E]     12.0519     18.114      0.665      0.506     -23.455      47.559
C(Q_7)[T..]     43.7133     29.366      1.489      0.137     -13.851     101.277
C(Q_7)[T.A]     43.3393     25.167      1.722      0.085      -5.993      92.671
C(Q_7)[T.B]     34.2678     25.174      1.361      0.173     -15.078      83.614
C(Q_7)[T.C]     27.2936     25.172      1.084      0.278     -22.049      76.637
C(Q_7)[T.D]     24.3086     25.188      0.965      0.335     -25.064      73.682
C(Q_7)[T.E]     24.6796     25.180      0.980      0.327     -24.679      74.038
C(Q_8)[T..]    -61.4560     25.623     -2.398      0.016    -111.682     -11.230
C(Q_8)[T.A]    -28.8995     18.178     -1.590      0.112     -64.532       6.733
C(Q_8)[T.B]    -13.8572     18.166     -0.763      0.446     -49.466      21.752
C(Q_8)[T.C]    -30.2651     18.167     -1.666      0.096     -65.877       5.347
C(Q_8)[T.D]     10.6715     18.146      0.588      0.556     -24.898      46.241
C(Q_8)[T.E]    -19.3526     18.179     -1.065      0.287     -54.987      16.282
C(Q_9)[T..]     21.5616     27.322      0.789      0.430     -31.995      75.118
C(Q_9)[T.A]     30.4354     21.870      1.392      0.164     -12.434      73.305
C(Q_9)[T.B]     11.0462     21.865      0.505      0.613     -31.814      53.907
C(Q_9)[T.C]      8.3137     21.871      0.380      0.704     -34.559      51.186
C(Q_9)[T.D]     17.0567     21.870      0.780      0.435     -25.813      59.927
C(Q_9)[T.E]     21.6592     21.881      0.990      0.322     -21.231      64.550
C(Q_10)[T..]    -9.9358     28.502     -0.349      0.727     -65.806      45.935
C(Q_10)[T.A]     1.3475     22.494      0.060      0.952     -42.745      45.440
C(Q_10)[T.B]    13.1787     22.489      0.586      0.558     -30.905      57.263
C(Q_10)[T.C]     3.4050     22.479      0.151      0.880     -40.658      47.468
C(Q_10)[T.D]     2.0411     22.491      0.091      0.928     -42.046      46.128
C(Q_10)[T.E]    -9.2718     22.494     -0.412      0.680     -53.364      34.821
C(Q_11)[T..]    45.9613     25.277      1.818      0.069      -3.586      95.509
C(Q_11)[T.A]    32.4523     20.360      1.594      0.111      -7.458      72.363
C(Q_11)[T.B]    33.1257     20.345      1.628      0.104      -6.754      73.006
C(Q_11)[T.C]    28.3460     20.351      1.393      0.164     -11.547      68.239
C(Q_11)[T.D]    27.3110     20.342      1.343      0.179     -12.563      67.186
C(Q_11)[T.E]    36.9193     20.357      1.814      0.070      -2.984      76.823
C(Q_12)[T..]    28.8364     25.251      1.142      0.253     -20.660      78.333
C(Q_12)[T.A]    29.6037     16.945      1.747      0.081      -3.611      62.819
C(Q_12)[T.B]    32.8989     16.917      1.945      0.052      -0.262      66.060
C(Q_12)[T.C]    42.8788     16.910      2.536      0.011       9.733      76.025
C(Q_12)[T.D]    67.0254     16.903      3.965      0.000      33.892     100.159
C(Q_12)[T.E]    31.5293     16.938      1.861      0.063      -1.673      64.732
C(Q_13)[T..]    49.9287     24.510      2.037      0.042       1.885      97.973
C(Q_13)[T.A]    20.5472     14.670      1.401      0.161      -8.209      49.303
C(Q_13)[T.B]    39.3155     14.632      2.687      0.007      10.633      67.998
C(Q_13)[T.C]    30.3714     14.636      2.075      0.038       1.681      59.062
C(Q_13)[T.D]    29.8045     14.654      2.034      0.042       1.080      58.529
C(Q_13)[T.E]    14.3926     14.666      0.981      0.326     -14.355      43.140
C(Q_14)[T..]     7.6252     30.788      0.248      0.804     -52.726      67.977
C(Q_14)[T.A]    16.4598     27.290      0.603      0.546     -37.034      69.953
C(Q_14)[T.B]    28.4217     27.296      1.041      0.298     -25.084      81.927
C(Q_14)[T.C]     7.6562     27.302      0.280      0.779     -45.861      61.173
C(Q_14)[T.D]    20.5481     27.287      0.753      0.451     -32.939      74.036
C(Q_14)[T.E]    22.1540     27.296      0.812      0.417     -31.352      75.660
C(Q_15)[T..]    31.6363     32.870      0.962      0.336     -32.796      96.069
C(Q_15)[T.A]     5.7298     25.609      0.224      0.823     -44.469      55.928
C(Q_15)[T.B]   -22.9165     25.609     -0.895      0.371     -73.115      27.282
C(Q_15)[T.C]   -12.4206     25.613     -0.485      0.628     -62.627      37.786
C(Q_15)[T.D]   -15.3446     25.612     -0.599      0.549     -65.550      34.861
C(Q_15)[T.E]   -13.5019     25.619     -0.527      0.598     -63.720      36.716
C(Q_16)[T..]    15.9885     36.774      0.435      0.664     -56.095      88.072
C(Q_16)[T.A]     2.0461     33.965      0.060      0.952     -64.532      68.624
C(Q_16)[T.B]     1.2718     33.954      0.037      0.970     -65.284      67.828
C(Q_16)[T.C]     0.8105     33.956      0.024      0.981     -65.750      67.371
C(Q_16)[T.D]    -2.7298     33.953     -0.080      0.936     -69.284      63.824
C(Q_16)[T.E]     0.9434     33.975      0.028      0.978     -65.655      67.542
C(Q_17)[T..]    -4.3510     23.480     -0.185      0.853     -50.377      41.675
C(Q_17)[T.A]    18.0882     18.792      0.963      0.336     -18.748      54.924
C(Q_17)[T.B]    17.3904     18.763      0.927      0.354     -19.389      54.170
C(Q_17)[T.C]    20.3235     18.776      1.082      0.279     -16.482      57.128
C(Q_17)[T.D]    48.6133     18.752      2.592      0.010      11.855      85.371
C(Q_17)[T.E]    33.8797     18.780      1.804      0.071      -2.934      70.693
C(Q_18)[T..]    43.1192     22.899      1.883      0.060      -1.767      88.006
C(Q_18)[T.A]     5.1215     14.780      0.347      0.729     -23.850      34.093
C(Q_18)[T.B]    22.6946     14.757      1.538      0.124      -6.233      51.622
C(Q_18)[T.C]    26.2445     14.741      1.780      0.075      -2.650      55.139
C(Q_18)[T.D]     8.9313     14.764      0.605      0.545     -20.010      37.872
C(Q_18)[T.E]    -2.3569     14.788     -0.159      0.873     -31.344      26.630
C(Q_19)[T..]   -16.7889     27.416     -0.612      0.540     -70.530      36.952
C(Q_19)[T.A]    36.2688     16.482      2.201      0.028       3.961      68.577
C(Q_19)[T.B]    32.9723     16.469      2.002      0.045       0.689      65.256
C(Q_19)[T.C]    55.5366     16.447      3.377      0.001      23.297      87.776
C(Q_19)[T.D]    37.3398     16.461      2.268      0.023       5.072      69.607
C(Q_19)[T.E]    54.2316     16.476      3.292      0.001      21.935      86.528
C(Q_20)[T..]    10.7237     23.645      0.454      0.650     -35.626      57.073
C(Q_20)[T.A]     4.5729     19.770      0.231      0.817     -34.180      43.325
C(Q_20)[T.B]    -0.8535     19.774     -0.043      0.966     -39.614      37.907
C(Q_20)[T.C]     9.3544     19.761      0.473      0.636     -29.381      48.089
C(Q_20)[T.D]     2.6077     19.771      0.132      0.895     -36.147      41.362
C(Q_20)[T.E]    32.2093     19.775      1.629      0.103      -6.554      70.973
C(Q_21)[T..]    25.7717     21.761      1.184      0.236     -16.885      68.428
C(Q_21)[T.A]     4.3785     15.418      0.284      0.776     -25.844      34.601
C(Q_21)[T.B]     2.6303     15.386      0.171      0.864     -27.530      32.790
C(Q_21)[T.C]    11.6471     15.376      0.757      0.449     -18.494      41.788
C(Q_21)[T.D]    -3.7395     15.388     -0.243      0.808     -33.903      26.424
C(Q_21)[T.E]    21.4483     15.391      1.394      0.163      -8.722      51.619
C(Q_22)[T..]    13.1911     22.921      0.576      0.565     -31.739      58.121
C(Q_22)[T.A]    31.8725     16.825      1.894      0.058      -1.108      64.853
C(Q_22)[T.B]    25.7965     16.804      1.535      0.125      -7.142      58.735
C(Q_22)[T.C]    25.0450     16.811      1.490      0.136      -7.907      57.997
C(Q_22)[T.D]    53.9184     16.813      3.207      0.001      20.962      86.875
C(Q_22)[T.E]    27.8008     16.819      1.653      0.098      -5.167      60.769
C(Q_23)[T..]    30.8198     25.499      1.209      0.227     -19.163      80.803
C(Q_23)[T.A]    20.7189     19.436      1.066      0.286     -17.381      58.818
C(Q_23)[T.B]    51.9196     19.424      2.673      0.008      13.845      89.994
C(Q_23)[T.C]    21.9793     19.437      1.131      0.258     -16.121      60.080
C(Q_23)[T.D]    47.8073     19.434      2.460      0.014       9.712      85.902
C(Q_23)[T.E]    35.3085     19.451      1.815      0.070      -2.819      73.436
C(Q_24)[T..]    20.2069     23.512      0.859      0.390     -25.881      66.294
C(Q_24)[T.A]    20.8705     18.216      1.146      0.252     -14.836      56.577
C(Q_24)[T.B]    18.1446     18.184      0.998      0.318     -17.499      53.788
C(Q_24)[T.C]    29.9224     18.176      1.646      0.100      -5.707      65.552
C(Q_24)[T.D]    18.3821     18.191      1.010      0.312     -17.277      54.041
C(Q_24)[T.E]    26.1874     18.218      1.437      0.151      -9.523      61.898
C(Q_25)[T..]     4.2163     22.814      0.185      0.853     -40.503      48.936
C(Q_25)[T.A]    -2.0230     16.760     -0.121      0.904     -34.875      30.829
C(Q_25)[T.B]     8.2034     16.758      0.490      0.624     -24.645      41.052
C(Q_25)[T.C]     2.2200     16.739      0.133      0.894     -30.591      35.031
C(Q_25)[T.D]     2.4134     16.747      0.144      0.885     -30.414      35.240
C(Q_25)[T.E]    -7.2682     16.767     -0.433      0.665     -40.135      25.598
C(Q_26)[T..]   -19.5978     26.933     -0.728      0.467     -72.392      33.196
C(Q_26)[T.A]   -25.8766     17.609     -1.470      0.142     -60.394       8.641
C(Q_26)[T.B]   -23.5715     17.599     -1.339      0.180     -58.068      10.925
C(Q_26)[T.C]   -18.7012     17.595     -1.063      0.288     -53.190      15.788
C(Q_26)[T.D]     3.3032     17.610      0.188      0.851     -31.216      37.822
C(Q_26)[T.E]   -29.3702     17.621     -1.667      0.096     -63.912       5.171
C(Q_27)[T..]   -36.3522     24.121     -1.507      0.132     -83.634      10.929
C(Q_27)[T.A]   -30.4410     19.542     -1.558      0.119     -68.748       7.866
C(Q_27)[T.B]   -28.9107     19.530     -1.480      0.139     -67.193       9.372
C(Q_27)[T.C]   -34.2053     19.516     -1.753      0.080     -72.460       4.049
C(Q_27)[T.D]   -38.5260     19.537     -1.972      0.049     -76.822      -0.230
C(Q_27)[T.E]   -37.6437     19.566     -1.924      0.054     -75.997       0.709
C(Q_28)[T..]    14.7522     22.070      0.668      0.504     -28.509      58.013
C(Q_28)[T.A]    59.6647     15.412      3.871      0.000      29.453      89.876
C(Q_28)[T.B]    49.9670     15.427      3.239      0.001      19.727      80.207
C(Q_28)[T.C]    40.7957     15.425      2.645      0.008      10.559      71.032
C(Q_28)[T.D]    45.3226     15.428      2.938      0.003      15.081      75.564
C(Q_28)[T.E]    44.5778     15.430      2.889      0.004      14.332      74.824
C(Q_29)[T..]   -64.7065     23.923     -2.705      0.007    -111.600     -17.813
C(Q_29)[T.A]   -50.4893     20.193     -2.500      0.012     -90.072     -10.907
C(Q_29)[T.B]   -47.7801     20.183     -2.367      0.018     -87.344      -8.217
C(Q_29)[T.C]   -33.5047     20.173     -1.661      0.097     -73.048       6.039
C(Q_29)[T.D]   -47.7737     20.190     -2.366      0.018     -87.351      -8.196
C(Q_29)[T.E]   -48.5429     20.216     -2.401      0.016     -88.171      -8.915
C(Q_30)[T..]   -53.4944     32.933     -1.624      0.104    -118.051      11.062
C(Q_30)[T.A]   -44.1347     27.694     -1.594      0.111     -98.420      10.150
C(Q_30)[T.B]   -41.5975     27.702     -1.502      0.133     -95.899      12.704
C(Q_30)[T.C]   -48.4554     27.695     -1.750      0.080    -102.742       5.832
C(Q_30)[T.D]   -51.4558     27.702     -1.857      0.063    -105.757       2.846
C(Q_30)[T.E]   -52.8768     27.710     -1.908      0.056    -107.193       1.440
C(Q_31)[T..]   -13.8864     23.440     -0.592      0.554     -59.833      32.060
C(Q_31)[T.A]    10.3670     15.954      0.650      0.516     -20.906      41.640
C(Q_31)[T.B]     5.6569     15.954      0.355      0.723     -25.616      36.930
C(Q_31)[T.C]     3.2319     15.953      0.203      0.839     -28.040      34.504
C(Q_31)[T.D]    23.0134     15.941      1.444      0.149      -8.233      54.260
C(Q_31)[T.E]     9.5738     15.981      0.599      0.549     -21.753      40.901
C(Q_32)[T..]    22.9343     21.365      1.073      0.283     -18.946      64.815
C(Q_32)[T.A]     9.2025     15.007      0.613      0.540     -20.215      38.620
C(Q_32)[T.B]     6.5804     15.008      0.438      0.661     -22.838      35.999
C(Q_32)[T.C]     0.4535     14.993      0.030      0.976     -28.936      29.843
C(Q_32)[T.D]    10.6632     15.001      0.711      0.477     -18.742      40.069
C(Q_32)[T.E]     5.6387     15.047      0.375      0.708     -23.856      35.134
C(Q_33)[T..]    32.1630     25.641      1.254      0.210     -18.099      82.425
C(Q_33)[T.A]    36.9673     19.556      1.890      0.059      -1.366      75.300
C(Q_33)[T.B]    44.4832     19.539      2.277      0.023       6.184      82.783
C(Q_33)[T.C]    38.5960     19.542      1.975      0.048       0.289      76.903
C(Q_33)[T.D]    48.2386     19.538      2.469      0.014       9.939      86.538
C(Q_33)[T.E]    40.3495     19.571      2.062      0.039       1.986      78.713
C(Q_34)[T..]    18.7737     26.892      0.698      0.485     -33.940      71.488
C(Q_34)[T.A]    11.1988     18.918      0.592      0.554     -25.883      48.281
C(Q_34)[T.B]     4.3390     18.929      0.229      0.819     -32.766      41.444
C(Q_34)[T.C]     7.4688     18.919      0.395      0.693     -29.616      44.553
C(Q_34)[T.D]    18.9917     18.927      1.003      0.316     -18.109      56.093
C(Q_34)[T.E]     8.0867     18.928      0.427      0.669     -29.016      45.190
C(Q_35)[T..]     6.7184     20.553      0.327      0.744     -33.570      47.007
C(Q_35)[T.A]    -0.4367     14.137     -0.031      0.975     -28.149      27.276
C(Q_35)[T.B]     2.7272     14.122      0.193      0.847     -24.954      30.409
C(Q_35)[T.C]    10.6058     14.113      0.751      0.452     -17.060      38.271
C(Q_35)[T.D]     3.9787     14.130      0.282      0.778     -23.719      31.676
C(Q_35)[T.E]     7.8371     14.181      0.553      0.581     -19.961      35.635
C(Q_36)[T..]    10.8221     24.262      0.446      0.656     -36.737      58.381
C(Q_36)[T.A]    12.6757     17.840      0.711      0.477     -22.293      47.645
C(Q_36)[T.B]    11.6129     17.832      0.651      0.515     -23.342      46.568
C(Q_36)[T.C]    16.0303     17.843      0.898      0.369     -18.945      51.006
C(Q_36)[T.D]    11.5246     17.857      0.645      0.519     -23.479      46.528
C(Q_36)[T.E]    21.7559     17.891      1.216      0.224     -13.313      56.825
C(Q_37)[T..]   -11.3110     22.176     -0.510      0.610     -54.781      32.159
C(Q_37)[T.A]     3.5970     15.969      0.225      0.822     -27.705      34.899
C(Q_37)[T.B]    19.6291     15.944      1.231      0.218     -11.623      50.882
C(Q_37)[T.C]     4.1140     15.962      0.258      0.797     -27.175      35.403
C(Q_37)[T.D]    16.9737     15.961      1.063      0.288     -14.313      48.260
C(Q_37)[T.E]    12.3403     15.979      0.772      0.440     -18.982      43.663
C(Q_38)[T..]    62.0032     27.971      2.217      0.027       7.174     116.832
C(Q_38)[T.A]    24.1631     17.014      1.420      0.156      -9.187      57.513
C(Q_38)[T.B]    17.1395     17.007      1.008      0.314     -16.197      50.476
C(Q_38)[T.C]    30.0956     16.993      1.771      0.077      -3.214      63.406